[build]
  publish = "."

[[redirects]]
  from = "/abaya-size-calculator"
  to = "/abaya-size-calculator.html"
  status = 200

[[redirects]]
  from = "/abaya-size-calculator/"
  to = "/abaya-size-calculator.html"
  status = 200
